# Generated by Django 5.0.4 on 2024-04-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('bin_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Bin ID')),
                ('name', models.CharField(max_length=100, verbose_name='Bin Name')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('waste_type', models.CharField(max_length=50, verbose_name='Waste Type')),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bin Capacity')),
                ('collect_freq', models.CharField(max_length=50, verbose_name='Collection Frequency')),
            ],
            options={
                'db_table': 'bin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('waste_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Waste ID')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('level', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Waste Level')),
            ],
            options={
                'db_table': 'waste',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('weather_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Weather ID')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('temp', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperature')),
                ('precip', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precipitation')),
                ('humid', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Humidity')),
            ],
            options={
                'db_table': 'weather_api',
                'managed': False,
            },
        ),
    ]
